### ISSUE TITLE
not working in India

### ISSUE THREAD

**Issue by vedantp2905** [cullenwatson/StaffSpy#25]
for this code:

from staffspy import scrape_staff
from pathlib import Path
session_file = Path(__file__).resolve().parent / "session.pkl"

staff = scrape_staff(
    company_name="openai",
    search_term="software engineer", # optional
    extra_profile_data=True, # fetch all past experiences, schools, & skills

    max_results=50, # can go up to 1000
    session_file=str(session_file), # save login cookies to only log in once (lasts a week or so)
    log_level=1,
)
filename = f"staff.csv"
staff.to_csv(filename, index=False)

**Getting error:**

Traceback (most recent call last):
  File "c:\Users\91917\Desktop\WeekendAI\Linkedin\app.py", line 5, in <module>
    staff = scrape_staff(
            ^^^^^^^^^^^^^
  File "C:\Users\91917\AppData\Local\Programs\Python\Python311\Lib\site-packages\staffspy\__init__.py", line 25, in scrape_staff
    staff = li.scrape_staff(
            ^^^^^^^^^^^^^^^^
  File "C:\Users\91917\AppData\Local\Programs\Python\Python311\Lib\site-packages\staffspy\linkedin\linkedin.py", line 186, in scrape_staff
ib\site-packages\staffspy\linkedin\linkedin.py", line 55, in get_company_id
    raise Exception(
Exception: ('Failed to find company openai', 500, '{"status":500}')
P

**Comment by cullenwatson** [comment]
works for me on multiple accounts. are you in another country besides US?

**Comment by cullenwatson** [comment]
also try some other companies like google and see if same error

**Comment by vedantp2905** [comment]
Yup, im currently in India. Would a VPN help?
Did try google, but I got the same errors.

**Comment by cullenwatson** [comment]
ok must be different endpoints. ill look into it

**Comment by cullenwatson** [comment]
can you try again with latest code? as it tries to search for company if that part fails now

**Comment by vedantp2905** [comment]
It's working now! I believe it is linkedin.com, but profiles take to linkedin.com/in

Also, any way I can find all employees of a given company. Per API call can fetch 1000 records, but OpenAI has around 3k employees. So, how can I prevent duplicates while scraping data?

**Comment by cullenwatson** [comment]
try finding the top locations and roles of openai. e.g. san francisco, london, new york city. and then for each location, try diff searcrh terms, e.g. accountant, software, finance. you just have to exhaustively search and be creative till you find them all.
