### ISSUE TITLE
Exception: driver not found for selenium

### ISSUE THREAD

**Issue by nguyentuc** [cullenwatson/StaffSpy#41]
Thank you for your contribution. However, when I set up a project with Python 3.10 and did pip install -U staffspy[browser] following the instruction, the log showed me an exception "Exception: driver not found for selenium".
Can you please take a look at this?

**Comment by cullenwatson** [comment]
@nguyentuc you need chromedriver installed

https://googlechromelabs.github.io/chrome-for-testing/#stable
