### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by VictorBauler** [cullenwatson/StaffSpy#46]
Thank you for the quick PR, you just need to fix a reference error on __init__.py:

Cell In[1], line 2
      1 from pathlib import Path
----> 2 from staffspy import LinkedInAccount, DriverType, BrowserType

File ~/.venv/lib/python3.11/site-packages/staffspy/__init__.py:9
      7 from staffspy.solvers.two_captcha import TwoCaptchaSolver
      8 from staffspy.utils.utils import set_logger_level, logger, Login
----> 9 from utils.driver_type import DriverType, BrowserType
     12 class LinkedInAccount:
     13     solver_map = {
     14         SolverType.CAPSOLVER: CapSolver,
     15         SolverType.TWO_CAPTCHA: TwoCaptchaSolver,
     16     }

ModuleNotFoundError: No module named 'utils'"

**On line 9 should be : staffspy.utils.driver_type**

**Comment by cullenwatson** [comment]
ok its good version 0.2.16
