### ISSUE TITLE
TooManyRequests: after scraping around 170 user profiles (account suspended) 

### ISSUE THREAD

**Issue by y-aoub** [cullenwatson/StaffSpy#49]
Hello,

After making less than 170 profile scraping requests (using a very good linkedin profile: 4200 followers + verified email etc.), the account being used gets suspended. This issue occurs consistently, suggesting that there may be a threshold for requests or detection mechanisms in place. It is important to investigate the root cause and implement measures to prevent account suspension :)

**Comment by cullenwatson** [comment]
have email proof it was suspended?

**Comment by y-aoub** [comment]
> have email proof it was suspended?

Yes

**Comment by cullenwatson** [comment]
paste the email here as proof thx

**Comment by cullenwatson** [comment]
<img width="928" alt="image" src="https://github.com/user-attachments/assets/2b164394-abd8-4fcf-8cc5-7be74446e3ae">
i just did 300 users, no issues. provide proof or logs or email or something when you reopen this issue.
