### ISSUE TITLE
Unable to download full record

### ISSUE THREAD

**Issue by hhchab** [cullenwatson/StaffSpy#9]
Why only part of members are scrapped ? : "2024-06-23 12:28:16,238 - StaffSpy - INFO - Scraped 999 staff members, with 869 hidedn LinkedIn Me"

**Comment by cullenwatson** [comment]
It means your LinkedIn account is bad. Not sure how they classify it but unverified email and a bunch of factors go into jt

**Comment by hhchab** [comment]
Thanks - tried from another profile and it worked well
